services:
  pets-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pets-app
    volumes:
      - .:/app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
