services:
  pets-mongodb:
    image: mongo:latest
    container_name: pets-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  pets-app:
    build: ./
    container_name: pets-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - pets-mongodb

volumes:
  mongodb_data:
